-- Ajouter les produits KVP021 à KVP050
INSERT INTO public.products (product_id, name, slug, description, brand_id, category_id, price, original_price, condition, size_eu, available_sizes, images, rating, review_count, stock_quantity) VALUES
('KVP021', 'GEL-NUNOBIKI Cosmos', 'asics-gel-nunobiki-cosmos', 'Découvrez une nouvelle dimension du style sportif avec ces baskets pour femmes signées ASICS.', (SELECT id FROM brands WHERE slug = 'asics'), (SELECT id FROM categories WHERE slug = 'femme'), 120.00, 150.00, 'excellent', 38, '["35,5", "36", "37", "37,5", "38", "39", "39,5", "40", "40,5"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/s/asics_women_gel_nunobiki_cosmospure_silver_6.jpg'], 4.7, 56, 16),
('KVP022', 'GEL-NUNOBIKI White', 'asics-gel-nunobiki-white', 'Alliance parfaite entre le style contemporain et la performance avec ces baskets signées ASICS.', (SELECT id FROM brands WHERE slug = 'asics'), (SELECT id FROM categories WHERE slug = 'femme'), 120.00, 150.00, 'excellent', 38, '["35,5", "36", "37", "37,5", "38", "39", "39,5", "40", "40,5"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/s/asics_women_gel_nunobiki_whitepure_silver_6.jpg'], 4.8, 43, 17),
('KVP023', 'GEL-QUANTUM 360 I Graphite Grey', 'asics-gel-quantum-360-i-graphite-grey', 'Entrez dans un monde de confort et d''innovation avec cette sneaker élégante d''ASICS.', (SELECT id FROM brands WHERE slug = 'asics'), (SELECT id FROM categories WHERE slug = 'femme'), 180.00, 220.00, 'excellent', 39, '["36", "37", "37,5", "38", "39", "39,5", "40", "40,5", "41,5", "42", "42,5"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/s/asics_women_gel_quantum_360_i_graphite_greyhazard_green_6.jpg'], 4.9, 67, 17),
('KVP024', 'Superstar Led Lights Comfort Closure Baby', 'adidas-superstar-led-lights-baby', 'Alliance parfaite entre innovation et style avec cette paire de baskets pour tout-petits.', (SELECT id FROM brands WHERE slug = 'adidas'), (SELECT id FROM categories WHERE slug = 'enfant'), 75.00, 95.00, 'excellent', 22, '["21", "22", "23", "23,5", "24", "25"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/d/adidas_infant_superstar_led_lights_comfort_closure_elastic_lace_cloud_white_core_black_cloud_white_11.jpg'], 4.8, 34, 4),
('KVP025', 'Superstar Led Lights CF EL Kids', 'adidas-superstar-led-lights-kids', 'Paire de baskets qui allie héritage sportif et innovation moderne pour enfants.', (SELECT id FROM brands WHERE slug = 'adidas'), (SELECT id FROM categories WHERE slug = 'enfant'), 80.00, 105.00, 'excellent', 31, '["30,5", "29", "30", "31", "31,5", "32"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/d/adidas_kids_superstar_led_lights_cf_el_cloud_white_core_black_cloud_white_10.jpg'], 4.6, 28, 12),
('KVP026', 'Gazelle Indoor Core Black', 'adidas-gazelle-indoor-core-black', 'Élégance intemporelle associée au confort moderne avec ces baskets signées Adidas.', (SELECT id FROM brands WHERE slug = 'adidas'), (SELECT id FROM categories WHERE slug = 'femme'), 120.00, 150.00, 'tres_bon', 38, '["36 2/3", "37 1/3", "38 2/3", "39 1/3", "40 2/3", "41 1/3", "36", "38", "40"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/d/adidas_women_gazelle_indoor_core_black_cream_white_gum_8.jpg'], 4.7, 41, 4),
('KVP027', 'BRMD Wonder Mauve', 'adidas-brmd-wonder-mauve', 'Alliance parfaite entre l''héritage et la modernité inspirée par une silhouette emblématique des années 80.', (SELECT id FROM brands WHERE slug = 'adidas'), (SELECT id FROM categories WHERE slug = 'femme'), 110.00, 140.00, 'bon', 38, '["36 2/3", "37 1/3", "38 2/3", "39 1/3", "40 2/3", "36", "38", "40"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/d/adidas_women_adidas_brmd_wonder_mauve_almost_yellow_wonder_quartz_8.jpg'], 4.5, 23, 6),
('KVP028', 'Superstar Bold Wonder Silver', 'adidas-superstar-bold-wonder-silver', 'Élégance intemporelle avec design emblématique et semelle plateforme moderne.', (SELECT id FROM brands WHERE slug = 'adidas'), (SELECT id FROM categories WHERE slug = 'femme'), 130.00, 170.00, 'excellent', 38, '["36 2/3", "37 1/3", "38 2/3", "39 1/3", "40 2/3", "41 1/3", "36", "38", "40", "42"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/d/adidas_women_superstar_bold_wonder_silver_cream_white_gum_9.jpg'], 4.8, 52, 15),
('KVP029', 'Superstar Bold Pink Tint', 'adidas-superstar-bold-pink-tint', 'Design emblématique revisité avec semelle plateforme pour un style affirmé.', (SELECT id FROM brands WHERE slug = 'adidas'), (SELECT id FROM categories WHERE slug = 'femme'), 130.00, 170.00, 'tres_bon', 38, '["36 2/3", "37 1/3", "38 2/3", "39 1/3", "40 2/3", "41 1/3", "36", "38", "40", "42"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/d/adidas_women_superstar_bold_pink_tint_cream_white_gum_8.jpg'], 4.6, 37, 18),
('KVP030', 'Superstar Bold Wonder Beige', 'adidas-superstar-bold-wonder-beige', 'Basket emblématique avec semelle plateforme audacieuse et finitions soignées.', (SELECT id FROM brands WHERE slug = 'adidas'), (SELECT id FROM categories WHERE slug = 'femme'), 130.00, 170.00, 'excellent', 38, '["36 2/3", "37 1/3", "38 2/3", "39 1/3", "40 2/3", "41 1/3", "36", "38", "40", "42"]'::jsonb, ARRAY['https://cdn.etrias.nl/media/cache/product_thumb_md/a/d/adidas_women_superstar_bold_wonder_beige_cream_white_gum_10.jpg'], 4.9, 73, 21);