// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjzzpxddbziuhcejqrro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqenpweGRkYnppdWhjZWpxcnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Nzk4MTEsImV4cCI6MjA3MzI1NTgxMX0.Qevjx5mVk_DM-U5fqiowljtcpndced2GS51BD7w4yg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});